spring.application.name=ai-service
server.port=8084

# Database Configuration (Single DB) - Even if not heavily used
spring.datasource.url=jdbc:mysql://localhost:3306/stayease_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=8369251323
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Feign Client Configuration
services.property-service.url=http://localhost:8082
services.user-service.url=http://localhost:8081
services.booking-service.url=http://localhost:8083

# Logging
logging.level.org.springframework.web=INFO
logging.level.feign=DEBUG